name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --verbose --release
      - run: cargo test --verbose --release

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-push: "false"
          skip-version-file: "true"
          output-file: "false"
          skip-commit: "true"
          skip-on-empty: "true"
          skip-tag: "true"

      - name: Create Release
        run: gh release create "$TAG_NAME" --notes "$BODY" target/release/bot target/release/notify
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GH_TOKEN: ${{ github.token }}
          TAG_NAME: ${{ steps.changelog.outputs.tag }}
          BODY: ${{ steps.changelog.outputs.clean_changelog }}

      - name: rsync bot
        uses: burnett01/rsync-deployments@5.2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          switches: -avzrP --delete
          path: target/release/bot
          remote_path: /apps/ah_bonus_bot/bot
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: rsync notify
        uses: burnett01/rsync-deployments@5.2
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          switches: -avzrP --delete
          path: target/release/notify
          remote_path: /apps/ah_bonus_bot/notify
          remote_host: ${{ secrets.SSH_HOST }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}

      - name: Restart service
        uses: appleboy/ssh-action@master
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo systemctl restart ah_bonus_bot.service
